services:

  # =======================
  # SQLite: optional local db
  # =======================
  bankmore-db:
    image: nouchka/sqlite3
    container_name: bankmore-db
    volumes:
      - ./data/sqlite:/data
    command: tail -f /dev/null  # SQLite is just a file, this keeps container alive
    restart: unless-stopped

  # =======================
  # Zookeeper for Kafka
  # =======================
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.7
    container_name: bankmore-zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    restart: unless-stopped

  # =======================
  # Kafka broker
  # =======================
  kafka:
    image: confluentinc/cp-kafka:7.7.7
    container_name: bankmore-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: unless-stopped
    volumes:
      - kafka-data:/var/lib/kafka/data

  # =======================
  # Kafka UI (Kowl)
  # =======================
  kafka-ui:
    image: quay.io/cloudhut/kowl:master
    container_name: bankmore-kowl
    depends_on:
      - kafka
    ports:
      - "8081:8080"
    environment:
      KAFKA_BROKERS: kafka:9092
      KOWL_LISTEN_ADDR: 0.0.0.0:8080
    restart: unless-stopped

  # =======================
  # BankMore API
  # =======================
  bankmore-api:
    build:
      context: src
      dockerfile: Dockerfile
    container_name: bankmore-api
    depends_on:
      - kafka
      - bankmore-db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      Kafka__BootstrapServers: kafka:9092
      Database__UseStringGuids: "true"
      ContaCorrente__NumeroInicial: "1000"
      Database__ConnectionString: "Data Source=/data/bankmore.db"
    ports:
      - "5189:8080"
      - "7085:443"
    restart: unless-stopped
volumes:
  kafka-data: